### ISSUE TITLE
Final behavior between PlayerCollisions and DefaultPlayerInteractionMap differs.

### ISSUE THREAD

**Issue by 8uurg** [SERG-Delft/jpacman-framework#50]
In the case that a pallet collides with a player the PlayerCollisions and DefaultPlayerInteractionMap react differently.

The PlayerCollisions CollisionMap will do nothing while the DefaultPlayerInteractionMap will instead act as if the player collided with a pallet.

**Comment by JWGmeligMeyling** [comment]
To use this framework for the builds on Devhub while this is not merged and deployed, I ask you the following:

Please update the version number in the pom file to something that identifies your group. Then use that version number in the pom file of your solution. I will deploy this version of the framework to our maven repositories. After the changes I will rebuild your failed builds. If the artefact/versions numbers are set correct, they should succeed then. Push this version number to a new commit and possibly on a new branch so that we can still merge in this PR :)

**Comment by avandeursen** [comment]
Fixed by #49.
